--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.897.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/11/2023 11:31:04 AM
-- Server version: 8.0.26
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE temere;

--
-- Drop table `batch`
--
DROP TABLE IF EXISTS batch;

--
-- Drop table `schedule`
--
DROP TABLE IF EXISTS schedule;

--
-- Drop table `sequence`
--
DROP TABLE IF EXISTS sequence;

--
-- Drop table `sequence_backup`
--
DROP TABLE IF EXISTS sequence_backup;

--
-- Drop table `users`
--
DROP TABLE IF EXISTS users;

--
-- Drop table `controls`
--
DROP TABLE IF EXISTS controls;

--
-- Drop table `devices`
--
DROP TABLE IF EXISTS devices;

--
-- Set default database
--
USE temere;

--
-- Create table `devices`
--
CREATE TABLE devices (
  device_id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'This is the index',
  device_name VARCHAR(24) NOT NULL COMMENT 'Device name ',
  device_description VARCHAR(255) DEFAULT NULL COMMENT 'More verbose device description',
  device_vendor VARCHAR(255) DEFAULT NULL COMMENT 'This is the vendor which assumes control of the device.  Eg Tuya.',
  device_controlid INT UNSIGNED DEFAULT NULL COMMENT 'This defines which of the available controls to use for the selected device',
  device_active TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Device activation state.  0=inactive and 1=active.',
  PRIMARY KEY (device_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 35,
AVG_ROW_LENGTH = 2340,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Top level table contining all devices';

--
-- Create index `device_name` on table `devices`
--
ALTER TABLE devices 
  ADD UNIQUE INDEX device_name(device_name);

--
-- Create table `controls`
--
CREATE TABLE controls (
  control_id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'This is the index',
  control_name VARCHAR(20) NOT NULL COMMENT 'Friendly name for this control',
  control_description VARCHAR(255) DEFAULT NULL COMMENT 'Verbose description of this control',
  device_id INT UNSIGNED DEFAULT NULL COMMENT 'Lookup from the devices table',
  device_guid VARCHAR(255) DEFAULT NULL COMMENT 'Unique device identifier (which may be specific to this control)',
  control_script VARCHAR(30) DEFAULT NULL COMMENT 'This is the script to run when this control is exercised.',
  control_active INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Set to 1 to enable this control.',
  PRIMARY KEY (control_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 28,
AVG_ROW_LENGTH = 1820,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Associates control scripts with each device';

--
-- Create index `control_name` on table `controls`
--
ALTER TABLE controls 
  ADD UNIQUE INDEX control_name(control_name);

--
-- Create foreign key
--
ALTER TABLE controls 
  ADD CONSTRAINT FK_controls_device_id FOREIGN KEY (device_id)
    REFERENCES devices(device_id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `users`
--
CREATE TABLE users (
  users_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  users_fullname VARCHAR(255) DEFAULT NULL,
  users_uid VARCHAR(255) NOT NULL COMMENT 'This is the actual username.',
  users_preferredname VARCHAR(255) DEFAULT NULL COMMENT 'This is used for image attribution in the Slides system and minor logging.',
  users_email VARCHAR(255) DEFAULT NULL,
  users_password VARCHAR(255) DEFAULT NULL,
  users_role INT UNSIGNED DEFAULT NULL,
  users_active TINYINT UNSIGNED DEFAULT 0 COMMENT '0 indicates yet to be approved by admin',
  users_added DATE DEFAULT NULL COMMENT 'Date this user registered',
  users_super TINYINT DEFAULT 0 COMMENT 'Set to 1 to enable account manipulation capability',
  PRIMARY KEY (users_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `sequence_backup`
--
CREATE TABLE sequence_backup (
  sequence_id INT UNSIGNED NOT NULL DEFAULT 0,
  schedule_id INT UNSIGNED NOT NULL COMMENT 'ID of the Schedule entry which generated this sequence record',
  cycle_id INT UNSIGNED NOT NULL COMMENT 'This is used to associate a turn on with its related turn off',
  entity_name VARCHAR(255) DEFAULT NULL COMMENT 'Same entity name as used in the Schedule',
  event_datetime DATETIME DEFAULT NULL COMMENT 'The date and time to fire this event',
  event_dayname VARCHAR(10) DEFAULT NULL COMMENT 'Decorative.  The day of the week corresponding to event date.',
  event_function TINYINT UNSIGNED NOT NULL COMMENT '0=Turn off and 1=Turn on',
  event_completed_date DATETIME DEFAULT NULL COMMENT 'This gets set when the event gets fired.',
  event_control VARCHAR(255) DEFAULT NULL COMMENT 'This contains the instruction or script to run when the event gets fired.',
  event_ontime VARCHAR(255) DEFAULT NULL COMMENT 'Decorative.  Value showing determined ontime once all the randomness is applied'
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 129,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `sequence`
--
CREATE TABLE sequence (
  sequence_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  schedule_id INT UNSIGNED NOT NULL COMMENT 'ID of the Schedule entry which generated this sequence record',
  device_id INT UNSIGNED NOT NULL COMMENT 'ID of the device being controlled.  Same as in the Schedule.',
  cycle_id INT UNSIGNED NOT NULL COMMENT 'This is used to associate a turn on with its related turn off',
  DEP_entity_name VARCHAR(255) DEFAULT NULL COMMENT 'Same entity name as used in the Schedule',
  event_datetime DATETIME DEFAULT NULL COMMENT 'The date and time to fire this event',
  event_dayname VARCHAR(10) DEFAULT NULL COMMENT 'Decorative.  The day of the week corresponding to event date.',
  event_function TINYINT UNSIGNED NOT NULL COMMENT '0=Turn off and 1=Turn on',
  event_completed_date DATETIME DEFAULT NULL COMMENT 'This gets set when the event gets fired.',
  DEP_event_control VARCHAR(255) DEFAULT NULL COMMENT 'This contains the instruction or script to run when the event gets fired.',
  event_ontime VARCHAR(255) DEFAULT NULL COMMENT 'Decorative.  Value showing determined ontime (duration) once all the randomness is applied',
  batch_id INT UNSIGNED DEFAULT NULL COMMENT 'Batch number for auditing only',
  PRIMARY KEY (sequence_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 35052,
AVG_ROW_LENGTH = 180,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'The sequence table contins all the event pairs built from the schedule.';

--
-- Create table `schedule`
--
CREATE TABLE schedule (
  schedule_id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'This is the index.',
  device_id INT UNSIGNED NOT NULL COMMENT 'Decice_id of the controlled entity.',
  schedule_enable INT UNSIGNED NOT NULL COMMENT 'Flag to indicate this schedule is active.',
  schedule_type TINYINT NOT NULL COMMENT '5=Weekday and 2=Weekend.',
  trigger_weighting INT NOT NULL COMMENT 'Enter the frequency of run for the schedule.',
  turn_on_time TIME NOT NULL DEFAULT '00:00:00' COMMENT 'Enter the turn on time.',
  turn_on_flex INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Enter the variability value for turn on time.',
  active_duration INT UNSIGNED NOT NULL COMMENT 'Enter the time to remain on in minutes.',
  active_duration_flex INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Enter the variability value for the duration.',
  comment VARCHAR(255) DEFAULT NULL COMMENT 'Description of this schedule entry.',
  `DEP-conflict_id` INT UNSIGNED DEFAULT NULL COMMENT 'If a schedule conflicy occurs, the ID of the conflictig record is placed here.  NULL means this schedule has no conflict.',
  is_dirty INT UNSIGNED DEFAULT 0 COMMENT 'Set this to True when the Schedule gets updated.  Used to advise Sequence rebuild needed.',
  PRIMARY KEY (schedule_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 112,
AVG_ROW_LENGTH = 528,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'This is the Schedule Table where the user registers desired events.';

--
-- Create table `batch`
--
CREATE TABLE batch (
  batch_id INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Batch number to use elsewhere',
  batch_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date this batch number was assigned',
  batch_requester VARCHAR(255) DEFAULT NULL COMMENT 'Name of the process requesting a batch number',
  PRIMARY KEY (batch_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 419,
AVG_ROW_LENGTH = 148,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'The batch table just assigns batch numbers to various activities';

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;